name: OWASP ZAP
on:
  push:
    branches:
      - dev
  pull_request: 
    types: [opened, synchronize, reopened]
    branches:
      - dev

jobs:
  build:
    name: owasp analysis 
    runs-on: ubuntu-latest
    steps:
     - name: analysis
       run: |
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
        tar -xvf ZAP_2.14.0_Linux.tar.gz
        cd ZAP_2.14.0
        ./zap.sh -cmd -quickurl https://shiazy18.github.io/shivam-website/ -quickprogress -quickout ./zap_report.html
        pwd
        dir

     - name: Upload build artifact
       uses: actions/upload-artifact@v4.3.3
       with:
         name: zap_report.html
         path: .
          
        

  

        
        
        

      
   
